name: symbiflow-env
channels:
  - defaults
  - litex-hub
dependencies:
  - litex-hub::capnproto-java=0.1.5_0012_g44a8c1e=20201104_165332
  - litex-hub::gcc-riscv64-elf-newlib=9.2.0=20201119_154229
  - litex-hub::symbiflow-yosys-plugins=1.0.0_7_g59ff1e6_23_g3a95697_17_g00b887b_0194_g40efa51=20201120_145821
  - litex-hub::prjxray-tools=0.1_2697_g0f939808=20201120_145821
  - litex-hub::prjxray-db=0.0_0239_gd87c844=20201120_145821
  - litex-hub::vtr=v8.0.0_3011_gb0223dc59=20201202_112618
  - litex-hub::yosys=0.9_5007_g2116c585=20201202_112618
  # swig is required to build the rapidyaml package
  # It can be removed once that is available in PyPi
  - swig
  - pip
  - pip:
    - -r file:../common/requirements.txt
    - -r file:requirements.txt
