name: symbiflow-env
channels:
  - defaults
  - litex-hub
dependencies:
  - litex-hub::yosys-uhdm=v0.0_93_ga57fae6
  - python=3.7
  - pip
  - pip:
    - -r ../common/requirements.txt
    - -r requirements.txt
